micronaut:
  application:
    name: capyverse_backend
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  router:
    static-resources:
      jsonschema:
        paths: classpath:META-INF/schemas
        mapping: /schemas/**
  cache:
    caffeine:
      caches:
        javaversion:
          expire-after-write: 1d
microstream:
  cache:
    my-cache:
      key-type: java.lang.Integer
      value-type: java.lang.String
endpoints:
  prometheus:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
